### ISSUE TITLE
Documentation on set_brightness is incorrect

### ISSUE THREAD

**Issue by apirek** [sparkfun/Qwiic_Alphanumeric_Py#1]
The documentation on QwiicAlphanumeric.set_brightness (https://github.com/sparkfun/Qwiic_Alphanumeric_Py/blob/594e4d99a8051d5af514cd74a15d2a9b8280dfb2/qwiic_alphanumeric.py#L479) and in qwiic_alphanumeric_ex04_set_brightness.py (https://github.com/sparkfun/Qwiic_Alphanumeric_Py/blob/594e4d99a8051d5af514cd74a15d2a9b8280dfb2/examples/qwiic_alphanumeric_ex04_set_brightness.py#L62) claim that a value 0 turns the display off.

This is incorrect, the value 0 specifies 1/16 duty cycle as per the datasheet, p.12 (https://www.holtek.com/documents/10179/116711/HT16K33v120.pdf).

Same as https://github.com/sparkfun/SparkFun_Alphanumeric_Display_Arduino_Library/issues/15

**Comment by sfe-SparkFro** [comment]
Thanks for catching this, will get that updated soon!
